---
- name: Start reproducer
  hosts: localhost
  tasks:

    - name: Start reproducer
      include_role:
        name: "../ansible-role-tripleo-ci-reproducer"
      vars:
        upstream_gerrit_user: "{{ upstream_gerrit_username }}"
        rdo_gerrit_user: "{{ rdo_gerrit_username }}"
