- name: Start docker
  service:
    name: docker
    state: started

# ansible module does not support removal of anon volumes at restart
# so we do a stop/start
#
- name: Stop up zuul and friends
  docker_compose:
    project_src: "{{ install_path }}"
    state: absent
    remove_volumes: true

- name: Start up zuul and friends
  docker_compose:
    project_src: "{{ install_path }}"
    state: present
    pull: "{{ pull | default(false) | bool }}"
