---
- name: Cleanup {{ zuul_src_dir }}
  file:
    path: "{{ zuul_src_dir|dirname }}"
    state: absent

- name: Ensure {{ zuul_src_dir }} exists
  file:
    path: "{{ zuul_src_dir|dirname }}"
    state: directory

# Git module with refspec doesn't do a fetch HEAD, which is required.
- name: Cloning zuul
  git:
    repo: "https://opendev.org/zuul/zuul"
    dest: "{{ zuul_src_dir }}"

- name: Checkout ref
  command: "{{ item  }}"
  with_items:
    - 'git fetch https://review.opendev.org/zuul/zuul {{ fetch_ref }}'
    - 'git checkout -b {{ tag_ref }} FETCH_HEAD'
  args:
    chdir: "{{ zuul_src_dir }}"
  failed_when: false
  when: fetch_ref is defined

- name: Install zuul
  pip:
    executable: pip-3
    chdir: "{{ zuul_src_dir }}"
    extra_args: "--user"
    name: "."
    state: present
