ci_jobs_config:
  standalone-dryrun:
    zuul_yaml:
      - project:
          check:
            jobs:
              - tripleo-ci-centos-9-standalone-dlrn-hash-tag

      - job:
          name: tripleo-ci-centos-9-standalone-dlrn-hash-tag
          parent: tripleo-ci-centos-9-standalone
          vars:
            mirror_fqdn: "{{ mirror_fqdn }}"
            zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn | default(mirror_fqdn) }}"
            pypi_fqdn: "{{ pypi_fqdn | default(mirror_fqdn) }}"
            package_mirror: "{{  package_mirror | default(omit) }}"
            dryrun: true

  standalone:
    zuul_yaml:
      - project:
          check:
            jobs:
              - tripleo-ci-centos-9-standalone-dlrn-hash-tag

      - job:
          name: tripleo-ci-centos-9-standalone-dlrn-hash-tag
          parent: tripleo-ci-centos-9-standalone
          timeout: 9000
          vars:
            mirror_fqdn: "{{ mirror_fqdn }}"
            zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn | default(mirror_fqdn) }}"
            pypi_fqdn: "{{ pypi_fqdn | default(mirror_fqdn) }}"
            package_mirror: "{{  package_mirror | default(omit) }}"

  hello_job:
    zuul_yaml:
      - job:
          name: hello-reproducer
          run: playbooks/run.yaml
      - project:
          check:
            jobs:
              - hello-reproducer
