---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create .ssh dir
      file:
        path: ~/.ssh
        state: directory
        mode: 0700
    - name: Add gerrits to known_hosts
      known_hosts:
        name: "[{{ item }}]:29418"
        key: "{{ lookup('pipe', 'ssh-keyscan
          -t rsa -p 29418 {{ item }}') }}"
      with_items:
        - review.openstack.org
        - review.rdoproject.org
        - gerrit
