---
# For libvirt
libvirt_volume_path: /opt/vm_images
libvirt_uri: qemu:///system
overcloud_nodes:
  - name: subnode-0
libvirt_nodepool: true
local_working_dir: "{{ install_path }}"
working_dir: "{{ install_path }}"
non_root_user: "{{ ansible_user }}"
non_root_group: "{{ ansible_user }}"
restore_snapshot: false
create_snapshot: false
